"""
Django settings for h5pxe project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5uul02oj&=smgc++*v7ub)p^*y4**h7%gpu-#5@+2z*rlakwo*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# FIXME: select all ifaces IPs.
ALLOWED_HOSTS = [ '127.0.0.1', '172.16.81.130' ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'managers.apps.ManagersConfig',
    'web.apps.WebConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'h5pxe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'h5pxe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'


# base repository directory
H5PXE_DIR_REPOSITORY_BASE = os.path.join(BASE_DIR, "repository")

# once an iso is registered, the needed files will be copied to this directory
H5PXE_DIR_REPOSITORY_HYPERVISOR = os.path.join(H5PXE_DIR_REPOSITORY_BASE, "hypervisor")

# only needed for pxelinux.0 / pxelinux cfg files.
H5PXE_DIR_REPOSITORY_PXE = os.path.join(H5PXE_DIR_REPOSITORY_BASE, "pxelinux.cfg")

# temp directory, when an iso is registered, the iso is mounted here atm...
H5PXE_DIR_TMP = os.path.join(H5PXE_DIR_REPOSITORY_BASE, "tmp")

H5PXE_CFG_DHCPD_FILE = "/etc/dhcp/dhcpd.conf"

H5PXE_SERVER_IFACE = "ens160"
H5PXE_SERVER_IP = "172.16.81.130"
H5PXE_SERVER_SUBNET = "172.16.81.0"
H5PXE_SERVER_NETMASK = "255.255.255.0"
H5PXE_SERVER_GW = "172.16.81.2"

H5PXE_DHCP = {
    'Server'    : H5PXE_SERVER_IP,
    'Subnet'    : H5PXE_SERVER_SUBNET,
    'Netmask'   : H5PXE_SERVER_NETMASK,
    'Gateway'   : H5PXE_SERVER_GW,
}
