# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=256, unique=True)),
                ('mac', models.CharField(max_length=18, unique=True)),
                ('vlan', models.PositiveIntegerField(default=0)),
                ('ip', models.CharField(max_length=32)),
                ('netmask', models.CharField(max_length=32)),
                ('gateway', models.CharField(max_length=32)),
                ('dns', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('INSTALLED', 'INSTALLED'), ('POSTCONF', 'POSTCONF'), ('DISABLED', 'DISABLED')], default='DISABLED', max_length=32)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='Hypervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('repository', models.CharField(max_length=256, unique=True)),
                ('status', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Kickstart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('info', models.CharField(max_length=256)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('script', models.CharField(max_length=256, unique=True)),
                ('status', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='hypervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Hypervisor'),
        ),
        migrations.AddField(
            model_name='host',
            name='kickstart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Kickstart'),
        ),
    ]
